title: AI Coding Blog
email: your-email@example.com
description: A simple blog powered by Jekyll and GitHub Pages.
baseurl: ""
url: "https://aicoding.host"

theme: minima

collections:
  posts:
    output: true
    permalink: /posts/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: Asia/Shanghai
