title: AI Coding Blog
description: A blog powered by Jekyll and GitHub Pages.
baseurl: ""
url: "https://aicoding.host"

collections:
  posts:
    output: true
    permalink: /posts/:title/

markdown: kramdown
kramdown:
  input: GFM

timezone: Asia/Shanghai
